name: ukk_room_booking
description: Aplikasi peminjaman ruangan UKK.

# Versi aplikasi Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  
  # State Management
  provider: ^6.0.5
  
  # Networking
  http: ^1.1.0
  dio: ^5.3.2
  
  # Storage
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  
  # Utilitas
  intl: ^0.18.1
  url_launcher: ^6.1.12
  flutter_dotenv: ^5.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  # Aset
  assets:
    - assets/images/
    
  # Fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
